# global config
global:
  scrape_interval:     15s
scrape_configs:
- job_name: 'prometheus'
  scrape_interval: 5s
  static_configs:
    - targets: ['172.17.0.1:3090']
- job_name: 'node'
  scrape_interval: 5s
  static_configs:
    - targets: ['172.17.0.1:3100']
- job_name: 'cadvisor'
  scrape_interval: 10s
  metrics_path: '/metrics'
  static_configs:
    - targets: ['172.17.0.1:3080']