version: '3.2'

services:
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.39.2 #功能:Docker監控容器資訊
    container_name: cadvisor
    restart: unless-stopped
    ports:
      - '3000:8080'
    volumes:
        - /:/rootfs:ro
        - /var/run:/var/run:rw
        - /sys:/sys:ro
        - /var/lib/docker/:/var/lib/docker:ro #必須指向docker目錄
    privileged: true

  node-exporter:
    image: prom/node-exporter:v1.1.2 #功能: 監控硬體資訊
    container_name: node-exporter
    restart: unless-stopped
    ports:
      - '9100:9100'
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($$|/)'
      - '--collector.textfile.directory=/node_exporter/prom'
    volumes:
      - /proc:/host/proc
      - /sys:/host/sys
      - /:/rootfs
      - ./etc/node_exporter/prom:/node_exporter/prom

  # process_exporter:
  #   image: ncabatoff/process-exporter:0.7.5
  #   container_name: process_exporter
  #   restart: always
  #   dns_search: .
  #   volumes:
  #     - ./proc:/host/proc
  #     - ./process-exporter/config:/config
  #   ports:
  #     - 9101:9256
  #   tty: true
  #   privileged: true
  #   command: /bin/process-exporter --procfs /host/proc -config.path config/process-

  process-exporter:
    container_name: process-exporter
    privileged: true
    image: ncabatoff/process-exporter:0.7.5
    volumes:
      - /proc:/host/proc
      - ./process-exporter/config:/config
    command:
      - '-config.path=/config/process-exporter.yml'
      - '--procfs=/host/proc'
    ports:
    - 9101:9256
